// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:b3ff8c66-e7a5-4ffb-9a78-001064e40f13",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_VYkooyv5q",
    "aws_user_pools_web_client_id": "3mvg01e8u2m7la004e42fa7dl9",
    "oauth": {}
};


export default awsmobile;
